FROM ruby:2.4.1-alpine3.6

LABEL maintainer="https://github.com/tootsuite/mastodon" \
      description="A GNU Social-compatible microblogging server"

ENV UID=991 GID=991 \
    RAILS_SERVE_STATIC_FILES=true \
    RAILS_ENV=production NODE_ENV=production

ARG LIBICONV_VERSION=1.15
ARG LIBICONV_DOWNLOAD_SHA256=ccf536620a45458d26ba83887a983b96827001e92a13847b45e4925cc8913178

ARG IMAGE_VERSION=
ARG MASTODON_VERSION=

EXPOSE 3000 4000

WORKDIR /mastodon

RUN apk -U upgrade \
 && apk add -t build-dependencies \
    build-base \
    icu-dev \
    libidn-dev \
    libtool \
    postgresql-dev \
    protobuf-dev \
    python \
 && apk add \
    ca-certificates \
    ffmpeg \
    file \
    git \
    icu-libs \
    imagemagick \
    libidn \
    libpq \
    nodejs-npm \
    nodejs \
    protobuf \
    su-exec \
    tini \
    yarn \
 && update-ca-certificates \
 && wget -O libiconv.tar.gz "http://ftp.gnu.org/pub/gnu/libiconv/libiconv-$LIBICONV_VERSION.tar.gz" \
 && echo "$LIBICONV_DOWNLOAD_SHA256 *libiconv.tar.gz" | sha256sum -c - \
 && mkdir -p /tmp/src \
 && tar -xzf libiconv.tar.gz -C /tmp/src \
 && rm libiconv.tar.gz \
 && cd /tmp/src/libiconv-$LIBICONV_VERSION \
 && ./configure --prefix=/usr/local \
 && make -j$(getconf _NPROCESSORS_ONLN)\
 && make install \
 && libtool --finish /usr/local/lib \
 && cd /mastodon \
 && rm -rf /tmp/* /var/cache/apk/*

COPY ./mastodon/Gemfile ./mastodon/Gemfile.lock ./mastodon/package.json ./mastodon/yarn.lock /mastodon/

RUN addgroup -g ${GID} mastodon && adduser -h /mastodon -s /bin/sh -D -G mastodon -u ${UID} mastodon

RUN bundle config build.nokogiri --with-iconv-lib=/usr/local/lib --with-iconv-include=/usr/local/include \
 && bundle install --deployment --without test development \
 && yarn --ignore-optional --pure-lockfile

COPY ./mastodon .

# assets are generated now - it saves a lot of startup time and removes
# the permission issue; /mastodon will be read-only except for tmp/
RUN SECRET_KEY_BASE=none SMTP_FROM_ADDRESS=none rails assets:precompile

COPY ./ct_bin/ /usr/local/bin/
RUN ct_install ${IMAGE_VERSION} ${MASTODON_VERSION}

RUN mkdir -p ./tmp && chown mastodon:mastodon -R ./tmp

ENTRYPOINT ["/usr/local/bin/ct_entry"]

USER mastodon
